### ISSUE TITLE
Refactor: Split members.json into separate files

### ISSUE THREAD

**Issue by frankharkins** [qiskit-community/ecosystem#424] opened 2023-06-28 13:24 UTC
### Problem

The ecosystem database is in [`members.json`](https://github.com/qiskit-community/ecosystem/blob/main/ecosystem/resources/members.json), and is difficult to for humans to edit, and causes merge conflicts.

### Proposed solution

@IceKhan13 and @1ucian0 have suggested splitting this out into different files (one file per repo).

Since [`manager.py`](https://github.com/qiskit-community/ecosystem/blob/main/ecosystem/manager.py) seems to access repos exclusively by tier or URL, I suggest the following structure:

```sh
ecosystem/resources/members
├── Tier.yaml  # List of URLs of repos
└── organisation
    └── repo-name.yaml
```

For example:

```sh
ecosystem/resources/members
├── Community.yaml
├── Extensions.yaml
├── Main.yaml
├── Qiskit
│   ├── qiskit-finance.yaml
│   └── qiskit-nature.yaml
└── unitaryfund
    └── mitiq.yaml
```

This should immediately remove merge conflict problems, but should also make it easier to avoid the `set-output` feature (see #406) as each step in the action can modify a file.

### Future work

- ~~Will still include a `members.json` as MVP, but eventually should have that compiled and released using an action.~~ Actually I think releasing `members.json` should be in MVP.
- Currently unsure how this fits with #228.

**Comment by mickahell** [comment] 2023-06-29 11:47
Don't you thing still having centralized files for url (`Tier.yaml`) will still favorized conflicts and so just moving the problem from a file to another ?

Why not having a folder per Tier and then inside having one yaml per project, something like :
```bash
ecosystem/resources/members
├── community
│   ├── my_super_project.yaml
│   ├── my_awesome_project.yaml
├── extensions
│   ├── my_super_extt.yaml
│   ├── my_awesome_ext.yaml
├── main
│   ├── qiskit-finance.yaml
│   └── qiskit-nature.yaml
└── index.yaml
```
The `index.yaml` would contains the list of the tier folders (community, extensions, main, ...). As the tier are static, we would not have any conflict this way.

- Also what the difference between `qiskit` and `main`, from my understanding `qiskit` is purely `main` ?
- I saw `unitaryfund` folder, do we need a folder per organisation or can we have a folder `partners` or something like ? If we create a folder per organization, we need to find a way to reference new folder without re-creating conflict.

---
- About #228, i think we should close it and keep the work on this new one.
- For the `set-output`, the problem is for the function in actions bash script as well. I think we need to review it more generally to have a better management of the vars.

**Comment by frankharkins** [comment] 2023-06-29 13:08
Thanks for your reply!

I'm thinking ahead a bit, but since most uses of the DAO are accessing by URL, my idea was to order the files by URL (the part after `github.com/`). Then file access becomes trivial and we can rid of the DAO in the future. The only other access type is by tier, hence the `Tier.yaml` files. These merge conflicts would just be one line, but it's still not zero-touch, which I agree is a drawback.

In terms of how things currently are, your suggestion makes more sense as that's the way `members.json` is structured. Can I suggest something like this?

```
└── tier
    └── organisation
        └── repo.yaml
```

For example:
```
ecosystem/resources/members
├── community
│   └── unitaryfund
│       └── mitiq.yaml
├── extensions
│   └── qiskit-community
│       └── prototype-qrao.yaml
└── main
    ├── Qiskit
    │   └── qiskit_ibm_runtime.yaml
    └── openqasm
        └── openqasm.yaml
```

That way there are no problems if two repos have the same name.

***

> ...what the difference between `qiskit` and `main`...

I'm not 100% sure, but I _think_ tier is just a level of endorsement. I can see that at least the `openqasm/openqasm` repo is considered "main", so main ≠ qiskit.

> ..do we need a folder per organisation... ...we need to find a way to reference new folder without re-creating conflict.

I think it would be good if filepath was unique to URL (e.g. `github.com/unitaryfund/mitiq`). We can just do an `os.walk` to find files; no index needed.

**Comment by frankharkins** [comment] 2023-06-29 13:13
@AbdullahKazi500 I won't assign just yet as it's not clear what the best solution is.

**Comment by mickahell** [comment] 2023-06-29 13:37
@frankharkins indeed something like should work fine :)

Just in the community as most of the project doesn't have organization, how do you see them ? Inside a subfolder `toto` or directly inside the `community` mixed with the organizations folders ?

**Comment by frankharkins** [comment] 2023-06-29 13:46
@mickahell After thinking on it a bit, I think the path of least resistance is to go with your original proposal. I think by trying to add more layers I was just making it more complicated.

Let's go with [your original idea](https://github.com/qiskit-community/ecosystem/issues/424#issuecomment-1612991533).

```
ecosystem/resources/members
├── community
│   ├── my_super_project.yaml
│   ├── my_awesome_project.yaml
├── extensions
│   ├── my_super_extt.yaml
│   ├── my_awesome_ext.yaml
├── main
│   ├── qiskit-finance.yaml
│   └── qiskit-nature.yaml
└── index.yaml
```

**Comment by Eric-Arellano** [comment] 2023-06-29 14:14
Yeah, I agree with the original idea. I do not recommend including the GitHub organization. It seems unnecessary. We've never had duplicate project names in the ecosystem and can control for that since we decide who can join or not.

@frankharkins are you still suggesting that we convert all these YAML files into one generated JSON file? So that it stays simple for qiskit.org to consume, and they can deal with JSON rather than YAML. That idea sounded good to me.

**Comment by frankharkins** [comment] 2023-06-29 14:44
@Eric-Arellano thanks! Yep I imagined either nightly or on push to main, an action would compile a JSON in the same form as we currently have, and add it as a release asset. Then qiskit.org can point to one link. I.e.

```diff
- https://raw.githubusercontent.com/qiskit-community/ecosystem/master/ecosystem/resources/members.json
+ https://github.com/qiskit-community/ecosystem/releases/latest/download/members.json
```

**Comment by mickahell** [comment] 2023-06-29 15:41
We need to find a simple way to stock this file, maybe more using artifact or something like

**Comment by Eric-Arellano** [comment] 2023-06-29 16:07
> Yep I imagined either nightly or on push to main, an action would compile a JSON in the same form as we currently have, and add it as a release asset. 

Probably even simpler is to have the file generated by the user, using a script, and checked in to version control. Then, qiskit.org points to that static URL.

Yes, there will be merge conflicts for the generated file. But the answer is to simply regenerate the generated file -- you should never try to manually fix the merge conflict.

This is how we generate our quite complex GitHub action YAML files for Pantsbuild. It's worked quite well for us! https://github.com/pantsbuild/pants/blob/main/src/python/pants_release/generate_github_workflows.py. It's nice being able to see in the PR how the final rendered asset will look.

**Comment by mickahell** [comment] 2023-06-30 07:28
Hmm ok, so we need a manual action to generate it. It's too much action for someone to git pull, git checkout and then git push and create a PR to do.

But It can also became the same problem as we have today and we will have so many branchs open (similar to the `batch_check_` branchs)

**Comment by frankharkins** [comment] 2023-06-30 10:24
The action can probably push directly to the `submission-*` branch, maybe triggering on PR approval.

**Comment by Eric-Arellano** [comment] 2023-06-30 12:18
I'm not following why we need a GitHub Action? When you change the YAML files, you are expected to also run a script to update the final JSON file. CI will check if the JSON file is out-of-date and error if so with instructions of how to run the script.

Yeah, that's a little manual. But keep it simple for now.

**Comment by mickahell** [comment] 2023-06-30 14:27
> The action can probably push directly to the `submission-*` branch, maybe triggering on PR approval.

If we put the generated general file who ref every project we will have conflict as well because every submission gonna edit it with their url :/

> I'm not following why we need a GitHub Action? When you change the YAML files, you are expected to also run a script to update the final JSON file. CI will check if the JSON file is out-of-date and error if so with instructions of how to run the script.

User never run any script, they only submitted issue and the Action does the who trick, then someone only need to validate the PR to add the project and so never no-one need to clone and commit anything so can't run any script. That's why we need an action to generated this file

Do you see what I mean ? I'm not sure to be totally clear ^^'

**Comment by mickahell** [comment] 2023-07-01 10:25
Or I'm wondering, can github Pages generated raw data html page by merging json ?
This way we would not have to store any general json file. And so we would not have any risk of conflict anymore. And no need any manual process to do.

**Comment by mickahell** [comment] 2023-07-01 10:45
> @Eric-Arellano thanks! Yep I imagined either nightly or on push to main, an action would compile a JSON in the same form as we currently have, and add it as a release asset. Then qiskit.org can point to one link. I.e.
> 
> ```diff
> - https://raw.githubusercontent.com/qiskit-community/ecosystem/master/ecosystem/resources/members.json
> + https://github.com/qiskit-community/ecosystem/releases/latest/download/members.json
> ```

If my point just above is not possible. The solution you refer @frankharkins looks good to me 🙂
Doing that from the main branch in order to stock the general file in the latest tag assets, would allow to not have conflict and to always be up to date with the actual main branch. Only require at most to click on a single button (no script, no git cmd, ...)
We could even schedule the action to be launch every day or every week in order to be fully automatic 🤖

**Comment by frankharkins** [comment] 2023-07-03 12:56
After trying to implement this, I've realised that we shouldn't have the "tier" information in two places. This is already causing problems: For example, `qiskit-ibm-provider` is "Main" on qiskit.org/ecosystem, but has the "Extension" badge.

In PR #426, I've gone with naming all TOML files the repo name, and having them all the same level.

**Comment by mickahell** [comment] 2023-07-06 16:30
Before closing this issue, just a quick question @frankharkins how do we manage the submission actually in PR :
- #388 
- #390
- #398 
- #402 

For the #402, I can close it and regenerate it (it's my QAMP project) but for the other do we resubmit them by hand ?

**Comment by mickahell** [comment] 2023-07-06 17:49
I re-created each submission but I couldn't delete the old branches
Maybe we can also clean the batch branches in order to restarted from this new way to go. What do you think ?

Anyway we can close this issue :)

**Closed by mickahell** 2023-07-06 17:49 UTC
Labels: enhancement
